config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  #Nav links
  get 'home/team', to: 'home#team'
  get 'home/contact', to: 'home#contact'
  get 'home/privacy', to: 'home#privacy'
  get 'home/terms', to: 'home#terms'
  get 'home/flatly', to: 'home#flatly'
  get 'home/basics', to: 'home#basics'


  devise_for :users

  resources :users, only: [:show, :edit, :update] do
    resources :avatars, only: [:create]
  end

  resources :events do 
    resources :attendances
    resources :event_pictures, only: [:create]
  end

  namespace :admin do
    root 'admin#index'
  end

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send

  has_many :attendances
  has_many :events, through: :attendances
  has_many :admins, foreign_key: 'admin_id', class_name: "Event"

  validates :first_name,
    presence: true,
    length: { in: 2..20 }
  validates :last_name,
    presence: true,
    length: { in: 2..20 }
    
  has_one_attached :avatar
       
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user, only: [:show]

  def show
    @user = current_user
    @events = Event.where(admin: @user)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = "Your profile has been updated!"
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "We cannot update your profile for the following reason(s):"
      render :edit
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :avatar)
  end

  def check_user
    @user = User.find(params[:id])
    unless current_user.id == @user.id
      flash[:warning] = "Where are you going mate 😁?"
      redirect_to root_path
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container my-5", style="max-width:400px">
      
      <%= form_for @user, html: { class: "form-signin mt-3" } do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Edit profile</h1>

        <div class="form-group">
          <%= f.label :first_name %><br />
          <%= f.text_field :first_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :last_name %><br />
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :description %><br />
          <%= f.text_area :description, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :profile_picture %><br />
          <%= f.file_field :avatar, class: "form-control" %>
        </div>

        <div class="actions mt-5">
          <%= f.submit "Edit", class: "btn btn-lg btn-primary btn-block" %>
        </div>

      <% end %>

</div>

app/views/users/show.html.erb
<div class="profile_canvas d-flex flex-column align-items-center">

  <img class="img-fluid rounded" src="https://picsum.photos/seed/picsum/1000/400" >
  <%if @user.avatar.attached?%>
    <%= image_tag(@user.avatar, :alt => 'real avatar', class:'img-thumbnail profile_pic rounded-circle m-3', style: 'height:200px;width:200px') %>
  <%else%>
    <%= image_tag('unnamed.jpg', :alt => 'default avatar', class:'img-thumbnail profile_pic rounded-circle m-3', style: 'height:200px;width:200px') %>
  <%end%>

  <h2><%= @user.first_name %> <%= @user.last_name %></h2>

  <%if @user.description?%>
    <div class="text-muted my-2"><%= @user.description %></div>
  <%else%>
    <strong class="my-2"><%= link_to "Add Bio", edit_user_path(@user) %></strong>
  <%end%>


  <div class="link_edit_profile">
    <%= link_to edit_user_path(current_user.id), class:"btn btn-light-custom-profile rounded d-flex mx-2 align-items-center", style:"height: 32px"  do %>
      <i class="fas fa-user mr-2"></i>
      <span>Edit Profile</span>
    <% end %>
  </div>

  <div class="link_personal_settings">
    <%= link_to edit_user_registration_path(current_user.id), class:"btn btn-light-custom-profile rounded d-flex mx-2 align-items-center", style:"height: 32px"  do %>
      <i class="fas fa-cog mr-2"></i>
      <span>Settings & Privacy</span>
    <% end %>
  </div>

</div>

<hr/>

<div class="container user_events my-3", style="max-width:400px">

  <% if @events.length > 0 %>

    <h4 class="text-center">All your events</h4>

    <% @events.each do |event| %>
      <div class="card text-center my-4">
        <h4 class="card-header text-primary"><%= event.title %></h4>
        <div class="card-body">
          <h5 class="card-title text-muted"><%= event.start_date.strftime("%B %d, %Y at %l:%M %P") %></h5>
          <% if event.event_picture.attached? %>
            <%= image_tag event.event_picture, alt: 'picture', class: "img-fluid rounded mx-2", style: 'height:auto;width:300px' %>
          <% end %>
          <p class="card-text"><%= event.description%></p>
          <%= link_to "See this event", event_path(event.id), class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
    
  <% else %>

    <div class="event_creation_via_profile d-flex flex-column align-items-center">
      <h5 class="my-4">You haven't organized any event yet!</h5>
      <%= link_to "Create your first event", new_event_path, class: "btn btn-primary" %>
    </div>

  <% end %>

</div>