config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  #Nav links
  get 'home/team', to: 'home#team'
  get 'home/contact', to: 'home#contact'
  get 'home/privacy', to: 'home#privacy'
  get 'home/terms', to: 'home#terms'
  get 'home/flatly', to: 'home#flatly'
  get 'home/basics', to: 'home#basics'


  devise_for :users

  resources :users, only: [:show, :edit, :update] do
    resources :avatars, only: [:create]
  end

  resources :events do 
    resources :attendances
    resources :event_pictures, only: [:create]
  end

  namespace :admin do
    root 'admin#index'
  end

end

app/models/event.rb
class Event < ApplicationRecord

  validates :start_date,
    presence: true,
    if: :future_date
  validates :duration,
    presence: true,
    numericality: { only_integer: true, greater_than: 0 },
    if: :multiple_of_five
  validates :title,
    presence: true,
    length: { in: 5..140 }
  validates :description,
    presence: true,
    length: { in: 20..1000 }
  validates :price,
    presence: true,
    numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 1000 }
  validates :location, presence: true
  
  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :admin, class_name: "User"

  has_one_attached :event_picture

  def multiple_of_five
    errors.add(:duration, "should be a multiple of 5") unless duration % 5 == 0
  end

  def future_date
    errors.add(:start_date, "can't be in the past") unless start_date > DateTime.now
  end

  def clean_start_date
    self.start_date.strftime("%B %d, %Y")
  end

  def clean_start_hour
    self.start_date.strftime("%l:%M %P")
  end

  def clean_end_hour
    date = self.start_date.to_datetime + (self.duration/1440.0)
    date.strftime("%l:%M %P")
  end

  def already_registered?(user)
    if self.attendances
      self.attendances.find_by(user: user.id) ? true : false
    else 
      puts "n'a pas attendances"
      return
    end
  end

  def is_admin?(user)
    self.admin.id == user.id ? true : false
  end

  def amount
    self.price * 100
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :is_admin?, only: [:edit, :update, :destroy]
  
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.admin = current_user
    if @event.save
      flash[:success] = "Your event has been created!"
      redirect_to event_path(@event.id)
    else
      flash.now[:alert] = "We cannot create the event for the following reason(s):"
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:success] = "Your event has been updated!"
      redirect_to event_path(@event.id), success: "Your event has been successfully updated!"
    else
      flash.now[:alert] = "We cannot update the event for the following reason(s):"
      render :edit
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to user_path(current_user.id)
  end

  private
  def event_params
    event_params = params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :event_picture)
    event_params[:start_date] = str_to_datetime(event_params[:start_date])
    event_params[:duration] = event_params[:duration].to_i 
    event_params[:price] = event_params[:price].to_i 
    return event_params
  end

  def str_to_datetime(str)
    DateTime.parse(str+'+01:00')
  end

  def is_admin?
    @event = Event.find(params[:id])
    unless @event.admin == current_user
      redirect_to event_path,
      warning: "Sorry bro! You can't just edit an event that's not yours to begin with 😁"
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= link_to "< Back", :back %>
      <br><br><br>
      <%= form_for @event, html: { class: "form-signin mt-3" }, multipart: true do |f| %>
        
        <h1 class="h3 mb-3 font-weight-normal text-center">Edit your Event</h1>
        
        <div class="form-group">
          <%= f.label :start_date %> <p class="red">* Require</p>
          <%= f.datetime_field :start_date, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :duration %> <p class="red">* Require duration multiple of 5</p>
          <%= f.text_field :duration, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :title %> <p class="red">* Require between 5 to 140 characters</p>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %> <p class="red">* Require between 20 to 1000 characters</p>
          <%= f.text_area :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :price %> <p class="red">* Require between 1 to 1000 in €</p>
          <%= f.text_field :price, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :location %><br />
          <%= f.text_field :location, class: "form-control" %>
        </div>

        <% if @event.event_picture.attached? %>
          <%= image_tag @event.event_picture, alt: 'picture', class: "img-fluid img-event rounded mx-auto d-block m-3" %>
        <% end %>
        
        <div class="form-group">
          <h5> Update event picture </h5>
          <%= f.file_field :event_picture, class: "form-control" %>
        </div>

        <div class="actions mt-5">
          <%= f.submit "Update", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<header class="masthead text-white text-center">
  <div class="column">
    <h2 class="mb-5">Hello there!</br></br>You wanna organize fake events for no reason, and still get a confirmation email anyway 😁?</h2>
    <%= link_to "Create your event here!", new_event_path, class: "btn btn-lg btn-primary" %>
  </div>
</header>

<div class="text-center my-5">
  <h4> ⬇️ Here are the latest Events ⬇️ </h4>
</div>

<div class="row justify-content-center text-center mb-5">
  <% @events.reverse.each do |event| %>

    <div class="card gossip-card m-3" style="width: 15rem">
      <div class="card-body">
        <h5 class="card-title"><%= event.title%></h5>
        <p class="card-text"><%= event.description%></p>
        <p class="card-text"><%= event.start_date%></p>
        <%= link_to "See this event", event_path(event.id), class: "btn btn-sm btn-primary" %>
      </div>
    </div>
    
  <% end %>
</div>

app/views/events/new.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for @event, html: { class: "form-signin mt-3" } do |f| %>
        <% if alert %>
          <div class="alert alert-danger" role="alert">
            <p><%= alert %></p>
            <ul class="list-unstyled">
              <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Create an Event</h1>
        
        <div class="form-group">
          <%= f.label :start_date %> <p class="red">* Require</p>
          <%= f.datetime_field :start_date, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :duration %> <p class="red">* Require duration multiple of 5</p>
          <%= f.text_field :duration, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :title %> <p class="red">* Require between 5 to 140 characters</p>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %> <p class="red">* Require between 20 to 1000 characters</p>
          <%= f.text_area :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :price %> <p class="red">* Require between 1 to 1000 in €</p>
          <%= f.text_field :price, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :location %><br />
          <%= f.text_field :location, class: "form-control" %>
        </div>

        <div class="form-group">
          <h5> Add event picture </h5>
          <%= f.file_field :event_picture, class: "form-control" %>
        </div>

        <div class="actions mt-5">
          <%= f.submit "Create", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">

  <div class="mt-3">
    <h1 class="text-center m-3">Title of this event : <%= @event.title %></h1>
    <p>Description: <%= @event.description %></p>
    <p>Creator: <%= @event.admin.email %></p>
    <p>Date: <%= @event.clean_start_date %></p>
    <p>From <%= @event.clean_start_hour %> to <%= @event.clean_end_hour %></p>
    <p>Duration: <%= @event.duration %> minutes</p>
    <p>Where? <%= @event.location %></p>
    <p>Price: <%= @event.price %> €</p>
  </div>

  <% if @event.is_admin?(current_user) %>
    <%= link_to "Event info", event_attendances_path(@event.id) , class: "btn btn-primary"%>  
  <% elsif @event.already_registered?(current_user) %>
    <%= link_to "Registered", new_event_attendance_path(@event.id) , class: "btn btn-primary"%>
  <% else %>
    <%= link_to "Register for this event", new_event_attendance_path(@event.id) , class: "btn btn-primary"%>
  <% end %>

  <% if @event.event_picture.attached? %>
    <%= image_tag @event.event_picture, alt: 'picture', class: "img-fluid img-event rounded mx-auto d-block m-3" %>
  <% end %>

</div>