config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  #Nav links
  get 'home/team', to: 'home#team'
  get 'home/contact', to: 'home#contact'
  get 'home/privacy', to: 'home#privacy'
  get 'home/terms', to: 'home#terms'
  get 'home/flatly', to: 'home#flatly'
  get 'home/basics', to: 'home#basics'


  devise_for :users

  resources :users, only: [:show, :edit, :update] do
    resources :avatars, only: [:create]
  end

  resources :events do 
    resources :attendances
    resources :event_pictures, only: [:create]
  end

  namespace :admin do
    root 'admin#index'
  end

end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :send_emails

  belongs_to :user
  belongs_to :event

  def send_emails
    UserMailer.email_to_admin(self.event.admin, self.user, self.event).deliver_now
    UserMailer.email_to_guest(self.user, self.event).deliver_now
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  
  before_action :authenticate_user!
  before_action :is_admin?, only: [:index]
  before_action :can_register?

  def index
    @event = Event.find_by(id: params[:event_id])
    @attendances = @event.attendances
  end
  
  def new
    @event = Event.find_by(id: params[:event_id])
    @amount = @event.amount

    if @amount == 0
      Attendance.create(event: @event, user: current_user, stripe_id: "Free")
      redirect_to event_path(@event),
      success: "You're now registered for this event!"
    end

    if @event.admin == current_user
      redirect_to event_path(@event),
      info: "You're the administrator of this event, no need to register ^^"
    end
  end

  def create
    @event = Event.find_by(id: params[:event_id])
        
    # Amount in cents originally
    @amount = @event.amount

    customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
      })
    
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'EUR',
    })

    Attendance.create(event: @event, user: current_user, stripe_id: customer)
    redirect_to event_path(@event),
    success: "You're now registered for this event!"

    rescue Stripe::CardError => e
      flash[:warning] = e.message
      redirect_to new_attendance_path
  end

  private

  def is_admin?
    @event = Event.find_by(id: params[:event_id])
    unless @event.admin == current_user
      redirect_to event_path(@event),
      warning: "Sorry pal, you can't see the attendees of this event if you don't have administrative rights on it."
    end
  end

  def can_register?
    @event = Event.find_by(id: params[:event_id])
    if @event.users.select{ |user| user == current_user }.count == 0
      return true
    else
      redirect_to event_path(@event),
      info: "You're already registered bro!"
    end
  end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/create.html.erb
<div class="container">
  <h1 class="text-center m-3">Thanks for your subscription </h1>
  <h2 class="text-center">You paid <strong><%= @event.price %> € </strong>!</h2>
  <p class="text-center m-3"><%= link_to "Return to this event >", event_path(@event.id) %></p>
</div>

app/views/attendances/index.html.erb
<div class="container">
  <h1 class="text-center m-3">EVENT INFO</h1>

  <%= link_to "Edit this event", edit_event_path(@event.id), :class => "btn btn-outline-success mx-4" %>
  <%= link_to "Delete this event", event_path(@event.id), :method => "delete", :class => "btn btn-outline-danger mx-4", :data => {:confirm => "Are you sure about that 😬?"} %>
  
  

  <h2 class="h3 mb-3 font-weight-normal text-center">All Attendees</h2>
  <div class="row justify-content-center">
    <% @attendances.each do |a| %>
      <div class="card border-light m-3 rounded custom-card" style="max-width: 25rem;">
        <div class="d-flex">
          <img class="mt-5 mb-2 mx-auto" src="https://robohash.org/<%= a.user.id %>.png?set=set4">
        </div>
        <div class="card-body">
          <p>First name : <%= a.user.first_name ? a.user.first_name : "Not mentionned" %></p>
          <p>Last name : <%= a.user.last_name ? a.user.last_name : "Not mentionned" %></p>
          <p>Description : <%= a.user.description ? a.user.description : "Not mentionned" %></p>
          <p>Email : <%= a.user.email ? a.user.email : "Not mentionned" %></p>
        </div>
       </div>
    <% end %>
  </div>



</div>

app/views/attendances/new.html.erb
<div class="container">
  <h1 class="text-center m-3"><%= @event.title %></h1>
  <div class="row justify-content-center">
    <%= form_tag event_attendances_path do %>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
        <label class="amount">
          <span>Amount: <%= @event.price.to_f %> €</span>
        </label>
      </article>

      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description=<%= @event.title %>
              data-amount=<%= @event.amount %>
              data-locale="fr"
              data-currency="eur"
              ></script>
    <% end %>
  </div>
</div>