config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  #Nav links
  get 'home/team', to: 'home#team'
  get 'home/contact', to: 'home#contact'
  get 'home/privacy', to: 'home#privacy'
  get 'home/terms', to: 'home#terms'
  get 'home/flatly', to: 'home#flatly'
  get 'home/basics', to: 'home#basics'


  devise_for :users

  resources :users, only: [:show, :edit, :update] do
    resources :avatars, only: [:create]
  end

  resources :events do 
    resources :attendances
    resources :event_pictures, only: [:create]
  end

  namespace :admin do
    root 'admin#index'
  end

end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg|%>

  <% if name == "notice" %>
  <div class="alert alert-success text-center" role="alert">
    <%= msg %>
  </div>

  <% elsif name == "alert" %>
    <div class="alert alert-danger text-center" role="alert">
      <%= msg %>
    </div>

  <% elsif name == "info" %>
    <div class="alert alert-info text-center" role="alert">
      <%= msg %>
    </div>

  <% elsif name == "warning" %>
    <div class="alert alert-warning text-center" role="alert">
      <%= msg %>
    </div>

  <%end%>

<%end%>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
        <ul class="list-inline mb-2">
          <li class="list-inline-item">
            <a href="<%= home_team_path %>">About</a>
          </li>
          <li class="list-inline-item">&sdot;</li>
          <li class="list-inline-item">
            <a href="<%= home_contact_path %>">Contact</a>
          </li>
          <li class="list-inline-item">&sdot;</li>
          <li class="list-inline-item">
            <a href="<%= home_terms_path %>">Terms of Use</a>
          </li>
          <li class="list-inline-item">&sdot;</li>
          <li class="list-inline-item">
            <a href="<%= home_privacy_path %>">Privacy Policy</a>
          </li>
        </ul>
        <p class="text-muted small mb-4 mb-lg-0">&copy; Eventbrite Replica 2020. All Rights Reserved.</p>
      </div>
      <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
        <ul class="list-inline mb-0">
          <li class="list-inline-item mr-3">
            <a href="#">
              <i class="fab fa-facebook fa-2x fa-fw"></i>
            </a>
          </li>
          <li class="list-inline-item mr-3">
            <a href="#">
              <i class="fab fa-twitter-square fa-2x fa-fw"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <i class="fab fa-instagram fa-2x fa-fw"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Header -->
  <nav class="navbar navbar-light bg-white static-top py-2">

    <div class="brand">
      <%= link_to image_tag('logo_homepage.png', :alt => 'logo', class:"navbar-brand"), root_path  %>
    </div>

    <div class="nav-items d-flex mr-auto navbar_static_links">
      <%= active_link_to "New event", new_event_path, class:"btn btn-light-custom-nav-links rounded-pill mr-2" %>
      <%= active_link_to "Basic Layout", home_basics_path, class:"btn btn-light-custom-nav-links rounded-pill mr-2" %>
      <%= active_link_to "Flatly", home_flatly_path, class:"btn btn-light-custom-nav-links rounded-pill" %>
    </div>

    <% if user_signed_in? %>

      <div class="link_personal_profile mr-2">
        <%= active_link_to user_path(current_user.id), class:"btn btn-light-custom-profile rounded-pill d-inline-flex align-items-center", style:"height: 38px"  do %>
          <%if current_user.avatar.attached?%>
            <span class="mr-2"><%= image_tag(current_user.avatar, :alt => 'real avatar', class:'rounded-circle', style: 'height:32px;width:32px') %></span>
          <%else%>
            <span class="mr-2"><%= image_tag('unnamed.jpg', :alt => 'default avatar', class:'rounded-circle', style: 'height:32px;width:32px') %></span>
          <% end %>
          <span><strong><%= current_user.first_name %></strong></span>
        <% end %>
      </div>

      <button class="btn btn-light dropdown-toggle rounded-circle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>

      <div class="dropdown-menu dropdown-menu-right text-left mr-3" aria-labelledby="dropdownMenuButton">

        <div class="link_personal_profile">
          <%= link_to user_path(current_user.id), class:"btn btn-light-custom-profile rounded d-flex mx-2 align-items-center", style:"height: 80px"  do %>
            <%if current_user.avatar.attached?%>
              <span class="mr-2"><%= image_tag(current_user.avatar, :alt => 'real avatar', class:'rounded-circle', style: 'height:64px;width:64px') %></span>
            <%else%>
              <span class="mr-2"><%= image_tag('unnamed.jpg', :alt => 'default avatar', class:'rounded-circle', style: 'height:64px;width:64px') %></span>
            <% end %>
            <div class="text-left">
              <strong><%= current_user.first_name %> <%= current_user.last_name %></strong><br>
              <span class="text-muted">See your profile</span>
            </div>
          <% end %>
        </div>

        <hr/>

        <div class="link_personal_settings">
          <%= link_to edit_user_registration_path(current_user.id), class:"btn btn-light-custom-profile rounded d-flex mx-2 align-items-center", style:"height: 32px"  do %>
            <i class="fas fa-cog mr-2"></i>
            <span>Settings & Privacy</span>
          <% end %>
        </div>

        <div class="link_logout">
          <%= link_to destroy_user_session_path, method: :delete, class:"btn btn-light-custom-profile rounded d-flex mx-2 align-items-center", style:"height: 32px"  do %>
            <i class="fas fa-sign-out-alt mr-2"></i>
            <span>Log Out</span>
          <% end %>
        </div>

      </div>
      
    <% else %>
      
      <div class="link_signup">
        <%= active_link_to new_user_registration_path, class:"btn btn-outline-success rounded d-flex mx-2 align-items-center", style:"height: 32px" do %>
          <span>Sign Up</span>
        <% end %>
      </div>

      <div class="link_login">
        <%= active_link_to new_user_session_path, class:"btn btn-outline-primary rounded d-flex mx-2 align-items-center", style:"height: 32px" do %>
          <span>Log In</span>
        <% end %>
      </div>

    <% end %>
          
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon-32x32.png') %>

    <!-- Styles -->
    <%= stylesheet_link_tag 'bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'main', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>

    <!-- Stripe JS-->
    <script src="https://js.stripe.com/v3/"></script>
    
  </head>

  <body>

  <%= render 'layouts/header' %>

  <%= render 'layouts/flash' %>

  <%= yield %>

  <%= render 'layouts/footer' %>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  </body>

</html>